name: Will she play it with me?
favicon: null
layout_spectrum: 0.7507
typography_spectrum: 0.72937
title: Will she play it with me?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050706'
    - '#2c3031'
    - '#525d61'
    - '#768183'
    - '#b3b7b8'
  brandStrength: 0.35821211570873857
  lightness: 0.5868994274642318
  saturation: 0.5017192829400301
  rhythmicContrast: 0.8919126947876066
purpose: []
