name: Will she play it with me?
favicon: null
layout_spectrum: 0.745847356505692
typography_spectrum: 0.7064204709604383
title: 'I play because I love games, she plays because she loves me.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.35821211570873857
  lightness: 0.5868994274642318
  saturation: 0.5017192829400301
  rhythmicContrast: 0.8919126947876066
purpose: []
